# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\ZEEL_DATA\Python_Project\VANI PDF TO AUDIOBOOK\VANI\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Text_Mode_Form import Ui_Text_Mode_Form
from PDF_Mode_Form import Ui_PDF_Mode_Form


class Ui_VANI(object):
    def setupUi(self, VANI):
        VANI.setObjectName("VANI")
        VANI.resize(600, 350)
        VANI.setMinimumSize(QtCore.QSize(600, 350))
        VANI.setMaximumSize(QtCore.QSize(600, 350))
        VANI.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        VANI.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon.fromTheme("Default")
        VANI.setWindowIcon(icon)
        VANI.setToolTipDuration(0)
        VANI.setStyleSheet("background-color: rgb(16, 142, 200);")
        VANI.setIconSize(QtCore.QSize(21, 24))
        VANI.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(VANI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 10, 481, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(28)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 230, 401, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(220, 170, 341, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(28)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 80, 381, 131))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(24)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(300, -20, 301, 51))
        self.label_5.setObjectName("label_5")
        self.label.raise_()
        self.label_4.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.label_5.raise_()
        VANI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VANI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 22))
        self.menubar.setObjectName("menubar")
        self.menuMode = QtWidgets.QMenu(self.menubar)
        self.menuMode.setObjectName("menuMode")
        VANI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VANI)
        self.statusbar.setObjectName("statusbar")
        VANI.setStatusBar(self.statusbar)
        self.Menu_Text_Mode = QtWidgets.QAction(VANI)
        self.Menu_Text_Mode.setObjectName("Menu_Text_Mode")
        self.Menu_PDF_Mode = QtWidgets.QAction(VANI)
        self.Menu_PDF_Mode.setObjectName("Menu_PDF_Mode")
        self.actionCredit = QtWidgets.QAction(VANI)
        self.actionCredit.setObjectName("actionCredit")
        self.menuMode.addAction(self.Menu_PDF_Mode)
        self.menuMode.addAction(self.Menu_Text_Mode)
        self.menubar.addAction(self.menuMode.menuAction())

        self.retranslateUi(VANI)
        QtCore.QMetaObject.connectSlotsByName(VANI)

        self.Menu_Text_Mode.triggered.connect(self.Open_Text_Mode)
        self.Menu_PDF_Mode.triggered.connect(self.Open_PDF_Mode)

    def Open_Text_Mode(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Text_Mode_Form()
        self.ui.setupUi(self.window)
        self.window.show()

    def Open_PDF_Mode(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_PDF_Mode_Form()
        self.ui.setupUi(self.window)
        self.window.show()

        
    def retranslateUi(self, VANI):
        _translate = QtCore.QCoreApplication.translate
        VANI.setWindowTitle(_translate("VANI", "VANI"))
        self.label.setText(_translate("VANI", "VANI - Way of Sound"))
        self.label_2.setText(_translate("VANI", "- ZEEL SHELADIYA"))
        self.label_3.setText(_translate("VANI", "Convter"))
        self.label_4.setText(_translate("VANI", "Text , PDF to Audio"))
        self.label_5.setText(_translate("VANI", "Go To Menu -> Mode -> Choose Your Mode And Enjoy"))
        self.menuMode.setTitle(_translate("VANI", "Mode"))
        self.Menu_Text_Mode.setText(_translate("VANI", "Text Mode"))
        self.Menu_PDF_Mode.setText(_translate("VANI", "PDF Mode"))
        self.actionCredit.setText(_translate("VANI", "Credit"))
    
    def printMessage(self):
        print("zeel")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VANI = QtWidgets.QMainWindow()
    ui = Ui_VANI()
    ui.setupUi(VANI)
    VANI.show()
    sys.exit(app.exec_())
